name: build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install stuff
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            binutils-aarch64-linux-gnu \
            build-essential \
            clang \
            libc6-arm64-cross \
            qemu-user-static
      - name: Run tests
        run: cargo test -- --nocapture
